"""empty message

Revision ID: c10f02b32b52
Revises: 5e10c09c8bf1
Create Date: 2020-11-14 22:32:55.219385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10f02b32b52'
down_revision = '5e10c09c8bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_venue')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_id')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artists', ['artist_id'], ['id'])
    op.add_column('artists', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
