"""empty message

Revision ID: e43e3cdf697e
Revises: d57831012a45
Create Date: 2020-11-14 22:38:00.549107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43e3cdf697e'
down_revision = 'd57831012a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'image_link')
    op.drop_column('artists', 'genres')
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
